version: "3.9"

services:
  db:
    image: mysql:5.7
    restart: always
    container_name: db
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hcdb
    ports:
      - "3366:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network
  cache:
    image: redis:latest
    restart: always
    container_name: redis
    ports:
      - "6300:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass root
    volumes:
      - cache:/data
    networks:
      - app-network
  webapp:
      container_name: webapp
      depends_on:
        - db
      build: ./webapp
      ports:
        - "3000:3000"
      networks:
        - app-network
      volumes:
        - ./webapp/src:/app:rw
  webapi:
    container_name: webapi
    deploy:
      mode: replicated
    depends_on:
      - db
      - cache
    build: ./api
    ports:
      - "8000:80"
    networks:
      - app-network
    volumes:
      - ./src:/var/www/html:rw
    environment:
      REDIS_HOST: cache
      REDIS_PORT: 6379
      REDIS_PASSWORD: root
#Docker Networks
networks:
  app-network:
    driver: bridge

#Docker volumes
volumes:
  src:
  dbdata:
  cache:
  webappsrc:
